# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_addres', models.IntegerField(default=0, verbose_name='Addres id')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hotel', models.IntegerField(default=0, verbose_name='hotel id')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='room id')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_start', models.DateField(default=django.utils.timezone.now, verbose_name='start of reservation')),
                ('reservation_finish', models.DateField(default=django.utils.timezone.now, verbose_name='end of reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.IntegerField(default=0, verbose_name='room id')),
                ('id_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Hotel', verbose_name='hotel id')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_telephone', models.IntegerField(default=0, verbose_name='telephone number')),
            ],
        ),
    ]
