# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_hotel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_finish',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_start',
            new_name='start_date',
        ),
    ]
