# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20161212_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end of reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start of reservation'),
        ),
    ]
